### ISSUE TITLE
Add type comments to every methode

### ISSUE THREAD

**Issue by IncredibleHannes** [IncredibleHannes/TPF2-Timetables#12]
In order to make document the code better, we need a documentation of every methods parameter and return type in the style of:
```
---@param hasTimetable function lineId -> boolean
-- returns [{vehicleID: lineID}]`
```

**Comment by Grisu118** [comment]
I like that, the annotation I added is from EmmyLua
https://emmylua.github.io/annotations/class.html

I use VSCode with the following plugin https://marketplace.visualstudio.com/items?itemName=sumneko.lua which supports the annotations

**Comment by IncredibleHannes** [comment]
Thanks, I added it to my VSCode as well. 
This inspired me to set up luacheck as a linter, which will be integrated into the build process with #15
