### ISSUE TITLE
Feature request: support color palettes

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#14]
To avoid white dots in the line oversight.

**Comment by IncredibleHannes** [comment]
Would be a matter of adding all the colours in the colour palettes to the stylesheet. 
https://github.com/IncredibleHannes/TPF2-Timetables/blob/develop/res/config/style_sheet/timetable_stylesheet.lua

Or finding a solution to make this dynamically.

**Comment by Gordon-Dry** [comment]
As there are at least two different color palette mods afaik a dynamic solution is to  be preferred.

**Comment by Grisu118** [comment]
I played around a little bit, seems to be impossible to access the available line colors within the style sheet. Also it is not possible to import timetableHelper :(

The only solution I found is the following: https://github.com/Grisu118/TPF2-Timetables/blob/grisu/feature-14-linecolors/res/config/style_sheet/timetable_colors_default.lua

I don't know what implications it have it we add a lot of stylesheet classes

**Comment by IncredibleHannes** [comment]
Same here, I was thinking about adding all possible colours in a for loop. that would be around 1 million style classes, but not sure if this would be bad for the game...

**Comment by Grisu118** [comment]
Already tried that, it crashed the game

**Comment by Vacuum-Tube** [comment]
Maybe it's possible using a **ColorChooserButton**
See also: https://www.transportfever.net/index.php?thread/16824-linienfarbe-colorchooserbutton/

**Comment by Gordon-Dry** [comment]
Time to test the new build.

**Comment by Gordon-Dry** [comment]
Well, perhaps that https://github.com/IncredibleHannes/TPF2-Timetables/tree/supportColourPalettes works with that "Color Palette" mod alone.
I tried it with an additional mod that also changes the lineColors, but "Color Palette" loaded afterwards - and timetable even later:
[NEP² - Natural Environment Professional](https://www.transportfever.net/filebase/index.php?entry/5942-natural-environment-professional-2/)
^ actually that mod entry seems to be in a maintenence state or the board database is borked because I cannot open that link now

The fact that the "Color Palette" mod does not simply overwrite stuff but injects into the array should make it failsafe.

Dunno what's the culprit here.

**Comment by Grisu118** [comment]
It looks like @IncredibleHannes copied the code from my branch. I did not create the pr due to the fact that it seems not to work for all colors. Some are still using the default color instead of the correct one. I had not the time to analyze, but it is on my todo list.

**Comment by Gordon-Dry** [comment]
In my example all lines are shown white in timetable UI.

**Comment by Grisu118** [comment]
Yes, @IncredibleHannes copied not all necessary parts from my branch... His branch cannot work like it is now

But I found also my issue. I switched the color mod in my savegame some time ago. The game keeps the color of the line, even if it is no longer available in the lineColors. So a lot of my lines using a color which was not part of marks color mod => displayed white. 
I try to verify the above by adding support for the other color mod too.

**Comment by Grisu118** [comment]
@Gordon-Dry You can try this branch: https://github.com/Grisu118/TPF2-Timetables/tree/grisu/feature-14-linecolors
It should work

**Comment by Gordon-Dry** [comment]
I will try it.

**Comment by Gordon-Dry** [comment]
Works.

**Comment by Gordon-Dry** [comment]
Imho you can open a PR for it.

**Comment by Grisu118** [comment]
> I try to verify the above by adding support for the other color mod too.

Is it excatly like that. So everything seems to work.
