### ISSUE TITLE
Not using arrSec correctly in timetable.getNextConstraint(...)

### ISSUE THREAD

**Issue by RoAnBu** [IncredibleHannes/TPF2-Timetables#17]
Hey, first of all great mod! This could really become a game changer! Thank you for hosting the project publicly on Github as well!

I read through most of the code (apart from the UI file) and most of it is easy to understand, good job! The function `timetable.waitingRequired(vehicle)` however is difficult to debug due to its size. I think this one could benefit for some refactoring at some point, maybe I can help.

I found what I think is a tiny bug in the following line:
https://github.com/IncredibleHannes/TPF2-Timetables/blob/0a3dda32739e1dbd9effe8a91f4ea95a033723e8/res/scripts/celmi/timetables/timetable.lua#L308

`diffSec = timetable.getDifference(timeSec, arrMin)` should probably be `diffSec = timetable.getDifference(timeSec, arrSec)`

I improved the function and the function below, maybe you want to use that for your refactoring:
```lua
---Find the next valid constraint for given constraints and time
---@param constraint table
---@param time number
---@return table
function timetable.getNextConstraint(constraint, time)
    local res = {diff = 40000, value = nil}
    local timeMin = tonumber(os.date('%M', time))
    local timeSec = tonumber(os.date('%S', time))
    for _, v in pairs(constraint) do
        local arrMin = v[1]
        local arrSec = v[2]
        local diffMin = timetable.getDifference(timeMin, arrMin)
        local diffSec = timetable.getDifference(timeSec, arrSec)
        local diff = (diffMin * 60) + diffSec
        if (diff < res.diff) then
            res = {diff = diff, value = v}
        end
    end

    return res.value
end

-- returns a value between 0 and 30
---comment
---@param a number
---@param b number
---@return number
function timetable.getDifference(a, b)
    local absDiff = math.abs(a - b)
    if absDiff < 30 then
        return absDiff
    else
        return 60 - absDiff
    end
end
```

At some point it could also make sense to just work with seconds and get rid of that os.date stuff but for now I think it's fine.

Do you consider opening a Discord Server? Might be a good place for people discussing things and helping each other, so less Issues for you 😄

**Comment by IncredibleHannes** [comment]
Hi RoAnBu,
Thanks for pointing that out!
I was planing some bigger refactoring anyways, the UI stuff and the waiting required could really need some work.
The idea with the discord server is very good, I will create one as soon as I got the time ;)

**Comment by IncredibleHannes** [comment]
Here the link for the discord server:
https://discord.gg/7KbVP8Fr6Z
