### ISSUE TITLE
Adding Arrival/Departure Timetable crashes the game

### ISSUE THREAD

**Issue by gentinettagian** [IncredibleHannes/TPF2-Timetables#21]
First of all, thank you for this awesome mod. It's incredible that this is possible within the constraints given. At first I was able to create some timetables without problems, however now I am spending a lot of time watching the loading screen as the game keeps crashing. 

The crash appears (approximately every second time) when I try to add a new Arrival/Departure slot to a line. I was hoping to create some nice Taktfahrplan (Zurich style as you mentioned in Heisenberch's video).. Have you encountered that error? I am trying to find out when exactly the crash is triggered, however this is quite difficult as I have to wait 10 minutes until the game is running again :'D

I am playing on macOS big sur using the new Vulkan version.

Edit: Added crashlog
[stdout.txt](https://github.com/IncredibleHannes/TPF2-Timetables/files/6057581/stdout.txt)

**Comment by IncredibleHannes** [comment]
sounds to me like the same bug as this?
https://github.com/IncredibleHannes/TPF2-Timetables/issues/3

**Comment by gentinettagian** [comment]
I thought it might be. Added it because for me the crash happens when adding a slot, where in #3 the game crashed when deleting a slot as far as I understood.

**Comment by IncredibleHannes** [comment]
Okay, I will continue investigating it, unfortunately, I have no idea what could cause it yet

**Comment by IncredibleHannes** [comment]
should be fixed with the next update ;)
