### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by lolluslollus** [IncredibleHannes/TPF2-Timetables#24]
Hello, I noticed that there are global variables here and there and they can cause issues. For example:
https://github.com/IncredibleHannes/TPF2-Timetables/blob/2125807bee8a56182f0143cf0af50aadea3271aa/res/scripts/celmi/timetables/timetable_helper.lua#L209
https://github.com/IncredibleHannes/TPF2-Timetables/blob/2125807bee8a56182f0143cf0af50aadea3271aa/res/scripts/celmi/timetables/timetable.lua#L262

**Comment by IncredibleHannes** [comment]
Thanks for pointing this out, I will try to remove all unnecessary global with the next refactoring!

**Comment by lolluslollus** [comment]
NP. I am actually surprised they don't crash the game, they always crashed things in my mods. Also game.interface is evil, I think they abandoned it.

**Comment by IncredibleHannes** [comment]
Yes I realised these later on.
I already have an issue for that:
https://github.com/IncredibleHannes/TPF2-Timetables/issues/11
