### ISSUE TITLE
Некорректная работа Расписания

### ISSUE THREAD

**Issue by romansmusic** [IncredibleHannes/TPF2-Timetables#25]
Всем привет! Прошу прощения что обращаюсь не на международном языке, к сожалению я в них не очень силен. 
Хочу выразить благодарность за создание столь замечательного мода! Благодаря Вам проводить игровое время намного интереснее:) 
Хочу поделится проблемой, к сожалению, я выявил ее поздно, потратив перед этим три вечера. 
Суть проблемы: мы создаем расписание для определенного маршрута: 
**Станция №1
прибытие - 00:00 отправление - 01:00
Станция №2 
прибытие - 01:50 отправление 02:30
Станция №3 
прибытие - 04:00 отправление 06:00**

Так вот, поезд по этому расписанию выдерживает только 1 и 3 станцию. 
На станцию №2 поезд приезжает не по графику, допустим в 1:40, но, вместо того, чтобы дождаться отправления в 02:30, он сразу, после загрузки пассажиров отправляется:( 

Помогите мне пожалуйста разобраться, может я что-то неправильно делаю?

**Comment by IncredibleHannes** [comment]
Здравствуй,
Google Translate, кажется, неплохо работает для перевода этого. Вы играете на большой карте?
Может быть та же проблема, что и в:
https://github.com/IncredibleHannes/TPF2-Timetables/issues/16
Я буду исследовать это дальше, однако, я не видел подобной проблемы раньше.
Спасибо, что обратили на это мое внимание.

**Comment by romansmusic** [comment]
Thank! I will wait for updates, because until the mod is playable for me. By the way, here's another information that can help: on my line the interval
 average movement 40 minutes. I only use one train per route. If the interval is 60 minutes or more, then I use two trains.

**Comment by romansmusic** [comment]
Yesterday I did a couple of checks:
1. I created a new small map and a three-stop line. The train followed the schedule completely.
2. I load my map and all the schedules are out of order, but it doesn't matter. I start to make the schedules and, in the time journal, all values ​​are at 0:00. I decided to wait until the time was updated and after that I began to draw up schedules. Trains switched to standby mode only at terminal (dead-end) stations. And then, not all trains :(
3. I tried to add a schedule for the express train and it worked.
It turns out that I have a selective problem. Some trains run on schedule, while others don't follow it at all.
Long range of motion could be a problem?

**Comment by IncredibleHannes** [comment]
should be fixed with #38
