### ISSUE TITLE
[Bug] Deletion of Arr/Dep-Entries produces Crash

### ISSUE THREAD

**Issue by Ehrenthomate** [IncredibleHannes/TPF2-Timetables#3]
Good Evening,

first, thank for this great mod, really good idea and implementation so for.

Unfortunately I just found a bug both in beta and the release version.
When trying to delete an Arr/Dep-Entry, the game crashes (see stdout - but it just says "An error ocurred" which is not helping).

I reproduced it with both beta and final version, while the game is running and when I paused.
A similar error occured, when trying to add an entry immediatly after removing one (while game was paused) - but again, i can not say anything how and why since the stdout only writes that nonsense...

If I had further information, I would tell you, but I just have none...maybe you can reproduce it and find the problem, you know your code :)

Greetings
ETH
[stdout.txt](https://github.com/IncredibleHannes/TPF2-Timetables/files/6051890/stdout.txt)

**Comment by IncredibleHannes** [comment]
Hi, 
thanks for posting it here. I already know this and spent some time on this, but wasn’t able to reproduce it. 
I had it randomly occurring once, but could not reproduce it since.
Anyone else experiencing this issue, please let me know here and together we might be able to pin this down to a specific number of steps that cause this error.

**Comment by IncredibleHannes** [comment]
Okay, I was able to reproduce it today on the current Beta version of the game. So it seems it has something to do with the changes they did on the current Beta, but I still have no idea what exactly is going wrong...

**Comment by IncredibleHannes** [comment]
Okay I am now able to reproduce it, still, no idea what's causing it.
