### ISSUE TITLE
Crash when adding "timetable"

### ISSUE THREAD

**Issue by splendorb** [IncredibleHannes/TPF2-Timetables#32]
Hallo! Firstly, super mod. Really great.

Unfortunately I have a total freeze on occasion when pressing the Add button to add a timetable slot, on a route that already has 1+ departure. There is no trace of the crash reason in sdout, and the crash does not always occur either. After forcing TPF to close, there is an "internal error" window - attached

Mac OS X 11.2.2.
[stdout.txt](https://github.com/IncredibleHannes/TPF2-Timetables/files/6070984/stdout.txt)
<img width="556" alt="error_after_forcequit" src="https://user-images.githubusercontent.com/38493503/109698244-819caa80-7b8f-11eb-9cc1-b6dcac91bf10.png">
![IMG_2153](https://user-images.githubusercontent.com/38493503/109698303-91b48a00-7b8f-11eb-8b19-9797215049c3.jpeg)

**Comment by IncredibleHannes** [comment]
resolved with #31
The update will be on the workshop page within the next days
