### ISSUE TITLE
Timetable not working, unbunching sometimes works

### ISSUE THREAD

**Issue by TwigsterTF2** [IncredibleHannes/TPF2-Timetables#39]
Hi,

First off, I just want to say this is a fantastic mod which should have been implemented in the game from the beginning. The issue I'm having with the timetable is that my trains seem to ignore it. I've tried implementing it exactly like Construction Gamer has in his video and also setup Arrival 0 Mins 0 Secs Departure 5 Mins 0 Secs then Arrival 5 Mins 0 Secs Departure 10 Mins 0 Sec, etc for the whole hour but that doesn't seem to work either. Maybe it's an issue with one of the mods I have installed, where you can slow time to 1/4 speed or 1/2 speed, which doesn't effect the game play speed if that makes sense. I can't remember the name of this.

Any other details let me know and I'll try to help.

**Comment by IncredibleHannes** [comment]
Can you check if this is solved with the new version I just uploaded to the workshop?

**Comment by TwigsterTF2** [comment]
Seems to be fixed now, thank you so much :)
