### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by muggy83** [IncredibleHannes/TPF2-Timetables#4]
I guess it would be nice to have German UI-Support (and other languages) for this great Mod.

**Comment by muggy83** [comment]
I started to put some work into it but I don´t have a clue how to open a new branch? Are you sure, this is activated for external users?

**Comment by IncredibleHannes** [comment]
Hi, this is a detailed tutorial on how to contribute to public repositories.
https://www.dataschool.io/how-to-contribute-on-github/
Multi-language support was on my list of future features, but I haven't started on it. I am curious about what you came up with!
