### ISSUE TITLE
Adding waypoints to the timetable

### ISSUE THREAD

**Issue by kelvindeschutter** [IncredibleHannes/TPF2-Timetables#41]
Could waypoints be added to the timetable in order to view the journey time between between two points? This would allow for easier optimsation of important junctions and overtaking points.

**Comment by Gordon-Dry** [comment]
I would say , as signals or waypoints are not supported by the reason how the mod works, you could do that task with the "Spitzkehre+++" mod which is a train station (and depot) without any platforms, just a piece of track.

But: that would mean the train needs to stop.
I don't know if that is okay for you.

**Comment by RoAnBu** [comment]
Maybe add a FAQ for questions like this?
