### ISSUE TITLE
Train is stopped at station before every passenger / cargo unit was unloaded.

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#42]
This results in not only that after "releasing the brake" passengers enter / cargo gets loaded, but also that passengers / cargo that came with that vehicle have to wait to get unloaded.

**Comment by IncredibleHannes** [comment]
We need to balance performance and accuracy here. With the new version, I stop the trains a bit earlier as people were reporting that the timetable sometimes misses some trains. Unfortunately, there is no satisfying solution that enables the mod to be accurate with the unloading, doesn't affect performance too much, and doesn't miss any trains on the way :/
