### ISSUE TITLE
Some i18n still not parsed

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#45]
See cursor
![Screen-2021-03-04_16-25-15](https://user-images.githubusercontent.com/29145213/109986762-57212d80-7d06-11eb-9333-be466299f425.png)

**Comment by IncredibleHannes** [comment]
Very strange, it works on my version. Anything special about your setup? Running on mac? The current beta branch of the game?

**Comment by Gordon-Dry** [comment]
Actually my version is 100% sync with the 1.1 release.

btw you should create a proper release, this is the full repo download, the same as you would download it from a branch.

**Comment by RoAnBu** [comment]
> btw you should create a proper release, this is the full repo download, the same as you would download it from a branch.

I mean you can just clone the repo and paste it into your mod folder. What would you expect in a release?

**Comment by IncredibleHannes** [comment]
https://github.com/IncredibleHannes/TPF2-Timetables/releases/tag/v1.1 The fixed version can also be downloaded from the release page on github ;)
Not sure what else you want?

**Comment by Gordon-Dry** [comment]
A release normally is a proper named file with only the contents that belong into the release.
No source code, no git stuff, no backups.

As long as it's set up that on the relase page it says "Source code" on the download link it's not a proper release.

I had that with other modders on other games as well. You will get used to it. ;)

**Comment by IncredibleHannes** [comment]
I was asking around and unfortunately, no one else was describing similar issues. Seems to be specific to your setup, some mod incompatibility maybe. But for now there is nothing I can do

**Comment by Gordon-Dry** [comment]
I will check again.
Perhaps it has already been fixed within the last couple of days.

Regarding the "proper release" thing:
![Release_Release_v1 2 1_·_IncredibleHannes_TPF2-Timetables_-_2021-03-16_19 17 48](https://user-images.githubusercontent.com/29145213/111359998-83d12f80-868c-11eb-84ee-a2ad437b8f6b.png)
This its how it looks.

As long as it says "Source code (zip)" it's not flagged as a release.
It's just the repo clone with everything. Incl. the stuff that should be ignored.

**Comment by IncredibleHannes** [comment]
Currently I'm not ignoring anything and therefore the whole repo is also the whole release

**Comment by Gordon-Dry** [comment]
Well, with latest 1.2.2 and "supportColourPalettes" branch merged on top:
![Screen-2021-03-23_16-15-37](https://user-images.githubusercontent.com/29145213/112170299-3d7f5180-8bf3-11eb-873f-ec57e69b3f29.jpg)

I have no idea.

**Comment by Enzojz** [comment]
I would provide a potential solution to this bug.

Don't call directly translator function _() directly from the gui functions. Instead, use a local variable the same level to "state" to store them so all strings are initialized at the loading. Then infere to these loaded strings.

An example would be my recently updated mods;
![image](https://user-images.githubusercontent.com/8238865/112623681-efee2900-8e2c-11eb-9f34-9945f2754078.png)

**Comment by IncredibleHannes** [comment]
I thought we were doing this already, but not in every case, as it turned out.. I'm currently fixing it and then I hopefully can incorporate it into the current v1.2.3 today
