### ISSUE TITLE
Feature request: optimize input field behaviour

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#46]
Actually the input is not very intuitive.

I prefer that the value is highlighted and ready to overwrite when clicked in the field.
Arrow buttons or PageUp, PageDown should increase/decrease the values.

**Comment by IncredibleHannes** [comment]
I have a look into it, but can't promise anything, as I need to work with what's already given by the GUI API.
Not sure if I can do anything

**Comment by Gordon-Dry** [comment]
Even using the mouse wheel as soon as the cursor is focussed inside the input field should change the value.

**Comment by IncredibleHannes** [comment]
Unfortunately, my research showed that whit the tools provided by the Game it is not possible to implement anything better/more intuitive than the current behaviour. Therefore will close the issue we need to wait for UG to add more functionality in future updates
