### ISSUE TITLE
Unbunch dont work

### ISSUE THREAD

**Issue by Flexmann** [IncredibleHannes/TPF2-Timetables#47]
Hey
first of all thank you very much for your fantastic work. The departure and arrival with the times works well, however, the trains do not stop at unbunch but continue normally. A recording of how long it takes from station to station would be fantastic. If I can help let me know.  and is a 24 Hour Clock possible?  Thanks

**Comment by IncredibleHannes** [comment]
Hi, 
can you provide more information about your unbunching setup? A screenshot maybe?
Second, that recording should be displayed as journey time already.
And what would be the use of a 24 Hour clock? There is no day-night cycle. As far as I see it this would only increase the configuration overhead for the timetable.

**Comment by Flexmann** [comment]
I will give more information tomorrow about the unbunch problem. 
right the 24 o'clock would not make so much sense.
The setup of the timetable with departure and arrival I just have to look again. do not look through yet.
thanks for the answers.

**Comment by Flexmann** [comment]
I shortly showed the problem in a clip. 
(https://youtu.be/ATxZgLcrPso)

**Comment by IncredibleHannes** [comment]
I can see the video because its private

**Comment by Flexmann** [comment]
yea sorry work now :)

**Comment by IncredibleHannes** [comment]
Not sure what I'm seeing in this video :/
When unbunch is set to 1:30 it means it Train B will depart 1:30 min after Train A's departure. If this was longer then 1:30 min ago it loads/unloads and departs right away. 

This means not that a train will always wait 1:30 min at a station

**Comment by Flexmann** [comment]
ohh sorry my bad. then I have misunderstood the function. 
Thanks for the quick help and correction
