### ISSUE TITLE
When list of stations is longer than the height of the UI, clicking on an entry makes the list jump to top

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#52]
Just stay where you are when clicked.

**Comment by IncredibleHannes** [comment]
#73

**Comment by Gordon-Dry** [comment]
Testing first ;)

**Comment by IncredibleHannes** [comment]
dosent work right now, semms to be a bug in the base game, I currently waiting for input to clarify this

**Comment by Gordon-Dry** [comment]
Likely. Vanilla-UI behaviour is not on top level.

**Comment by Gordon-Dry** [comment]
You said you're waiting for input.
From UG?

**Comment by IncredibleHannes** [comment]
Tried contacting UG, but haven't heard back so far, also posted it in Discord to see if any other modder had similar issues. 
At the current state, it doesn't seem possible to implement it, therefore I have put it on hold until I come up with a better idea or get some input from outside about this issue

**Comment by IncredibleHannes** [comment]
There seems to ba a bug in the Game UI, I found a workaround to avoid the bug and #73 should be solving this issue
