### ISSUE TITLE
When frequency is over 60 minutes, timetable just shows the minutes, not the hour

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#61]
66:05 is shown as 6:05

Is it only shown as, or does the mod also calculate with as?

**Comment by IncredibleHannes** [comment]
It is just the value of the game displayed there, should be possible to make it also show all minutes

**Comment by IncredibleHannes** [comment]
https://github.com/IncredibleHannes/TPF2-Timetables/pull/64
