### ISSUE TITLE
Maybe more info about the timetable interface not working after loading a savegame.

### ISSUE THREAD

**Issue by eagle1839** [IncredibleHannes/TPF2-Timetables#62]
i played for a while with the mod and i have noticed that after loading a savegame the timetable interface is not opening anymore. 
Because i save my game every few years i have some older savegames and there i noticed some strange things.

first of all. In the station list one of my station names is calles "Albert Thomas" When i click on it i got the information  about a station that has not the name "Albert Thomas" So it seems that there is going someting wrong with an identy ID. After waiting several times "Albert Thomas" does no longer exists and this is the moment my savegames got broken and i can't open the timetable interface after loading a savegame.

Than is there an opposite station on the line  of the so called "Albert Thomas" station. When i click on this station my game crashes and i got a lua exeption error. `res/sctipts/celmi/timetables/timetable_helper.lua:185: attempt to index a nil value  `

I'am not sure of those things have really to do with each other but i hope this information will help you too solve some problems.

**Comment by LamaAlpen2001** [comment]
I'm gonna add my experiment:
After loading my save-game I opened the console and then tried to open the timetable.
I got `/res/scripts/celmi/timetables/timetable_helper.lua:281: attempt to index local 'res' (a nil value)`. 
Given there wasn't any crash, it isn't much but maybe it helps.

**Comment by IncredibleHannes** [comment]
should be fixed now
