### ISSUE TITLE
Feature request: when in input field for "minutes", pressing TAB should jump to "seconds"

### ISSUE THREAD

**Issue by Gordon-Dry** [IncredibleHannes/TPF2-Timetables#66]
Just "steal" the input binding and do not trigger the vanilla behaviour when pressing TAB key.
If possible.
And when the cursor jumps to the next input field, select the contents to be able to just type and overwrite.

No mouse-pushing necessary when entering numbers ;)

**Comment by IncredibleHannes** [comment]
Would be great to have such a feature
Unfortunately, my research showed that whit the tools provided by the Game it is not possible to implement anything better/more intuitive than the current behaviour. Therefore will close the issue we need to wait for UG to add more functionality in future updates
