### ISSUE TITLE
Train doesn't leave station at time

### ISSUE THREAD

**Issue by Melectro1** [IncredibleHannes/TPF2-Timetables#88]
I have saved the game about 3 minutes before the train is arriving the station seen in attached images.
When loading the saved game, I watch the train arrive at 04:45 and directly it starts to unload. At departure time nothing happens, the train waits to next departure and that creates a mess with others trains along this line. 
What is wrong?

![20210528052120_1](https://user-images.githubusercontent.com/84949550/119925928-a7f79980-bf76-11eb-9dd2-e0e948438cb8.jpg)
![20210528052154_1](https://user-images.githubusercontent.com/84949550/119925931-a9c15d00-bf76-11eb-95d8-c18cd1b0ac7e.jpg)
![20210528052226_1](https://user-images.githubusercontent.com/84949550/119925937-acbc4d80-bf76-11eb-83ae-b7c78386f323.jpg)

**Comment by IncredibleHannes** [comment]
Hi,
easy answer, the timetable is wrong. 
Someone else already pointed out this bug to me
#89 is solving this issue, however I still need to test it properly before I can publish the update to steam
